"""
Django settings for podcasts_site project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'podcasts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'podcasts_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'podcasts_site.wsgi.application'

GMAIL_USERNAME = os.environ['GMAIL_USERNAME']
GMAIL_PASSWORD = os.environ['GMAIL_PASSWORD']

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

ASSETS_FOLDER_NAME = 'assets'

PROD_ENV = os.environ['ENV'] == "PROD"
if PROD_ENV:
    MEDIA_ROOT = os.path.join(BASE_DIR, ASSETS_FOLDER_NAME)
else:
    MEDIA_ROOT = os.path.join('/home/jace/1_Home/podcasts_website', ASSETS_FOLDER_NAME)

Path(MEDIA_ROOT).mkdir(parents=True, exist_ok=True)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
URL_ROOT = "/"
STATIC_URL = f"{URL_ROOT}static/"

MEDIA_URL = f'{URL_ROOT}media/'

print(f'[settings.py] ASSETS_FOLDER_NAME set to {ASSETS_FOLDER_NAME}')
print(f'[settings.py] MEDIA_ROOT set to {MEDIA_ROOT}')
print(f'[settings.py] URL_ROOT set to {URL_ROOT}')
print(f'[settings.py] STATIC_URL set to {STATIC_URL}')
print(f'[settings.py] MEDIA_URL set to {MEDIA_URL}')

PROD_HOST = None
if PROD_ENV:
    PROD_HOST = os.environ['PROD_HOST']
    LAN_HOST = os.environ['LAN_HOST']
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ['POSTGRES_USER'],
            'PASSWORD': os.environ['POSTGRES_PASSWORD'],
            'HOST': f"{os.environ['COMPOSE_PROJECT_NAME']}_db",
            "PORT": "5432",
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': f'{MEDIA_ROOT}/db.sqlite3',
        }
    }

HOST = PROD_HOST if PROD_ENV else "localhost"
ALLOWED_HOSTS = [HOST, LAN_HOST]
HTTP_AND_FQDN = f"https://{HOST}" if PROD_ENV else f"http://{HOST}"
CSRF_TRUSTED_ORIGINS = [HTTP_AND_FQDN]
if not PROD_ENV:
    HTTP_AND_FQDN += ":8000"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
