# Generated by Django 4.2.16 on 2024-09-04 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='youtubepodcast',
            name='one_process_in_progress',
        ),
    ]
