# Generated by Django 5.1 on 2024-09-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubepodcastvideo',
            name='identifier_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
