# Generated by Django 5.1 on 2024-12-28 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_loggingfilepath_youtubedlpwarnerror_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubedlpwarnerror',
            name='debug_file_path',
        ),
        migrations.RemoveField(
            model_name='youtubedlpwarnerror',
            name='error_file_path',
        ),
        migrations.RemoveField(
            model_name='youtubedlpwarnerror',
            name='warn_file_path',
        ),
    ]
