# Generated by Django 5.1 on 2024-12-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_remove_youtubedlpwarnerror_debug_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubedlpwarnerror',
            name='video_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
