# Generated by Django 5.1.1 on 2024-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_alter_youtubedlperror_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubepodcastvideo',
            name='manually_hide',
            field=models.BooleanField(default=False),
        ),
    ]
