# Generated by Django 4.2.16 on 2024-09-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_youtubepodcastvideo_manually_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubePodcastTitlePrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(default=None, max_length=1000, null=True)),
                ('priority', models.IntegerField(default=None)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.youtubepodcast')),
            ],
        ),
        migrations.AddConstraint(
            model_name='youtubepodcasttitleprefix',
            constraint=models.UniqueConstraint(fields=('podcast', 'priority'), name='unique_podcast_title_prefix_priority'),
        ),
    ]
