# Generated by Django 5.1 on 2025-01-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_youtubedlpwarnerror_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubedlpwarnerror',
            name='video_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
