# Generated by Django 5.1.1 on 2024-09-26 23:41

import django.db.models.deletion
import podcasts.views.pstdatetimefield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_youtubepodcasttitleprefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubepodcastvideo',
            name='url',
            field=models.CharField(max_length=10000, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubepodcastvideo',
            name='video_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.CreateModel(
            name='DuplicateYouTubePodcastVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=1000, unique=True)),
                ('filename', models.CharField(max_length=1000)),
                ('original_title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('date', podcasts.views.pstdatetimefield.PSTDateTimeField()),
                ('identifier_number', models.PositiveBigIntegerField()),
                ('grouping_number', models.IntegerField()),
                ('url', models.CharField(max_length=10000, unique=True)),
                ('extension', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=10000, null=True)),
                ('size', models.PositiveBigIntegerField()),
                ('hide', models.BooleanField(default=False)),
                ('manually_hide', models.BooleanField(default=False)),
                ('duration', models.PositiveBigIntegerField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.youtubepodcast')),
            ],
        ),
    ]
