# Generated by Django 5.1 on 2025-09-15 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0005_alter_youtubedlpwarnerror_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWithNewDateFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=10000)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.youtubepodcast')),
            ],
        ),
    ]
