# Generated by Django 5.1 on 2026-01-16 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_videowithnewdateformat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TroubleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('levelno', models.IntegerField(default=30)),
                ('video_unavailable', models.BooleanField(null=True)),
                ('video_id', models.CharField(default=None, max_length=100, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.youtubepodcast')),
            ],
        ),
        migrations.CreateModel(
            name='WarnStreamHandlerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('video_id', models.CharField(default=None, max_length=100, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.youtubepodcast')),
            ],
        ),
        migrations.DeleteModel(
            name='YouTubeDLPWarnError',
        ),
    ]
