# Generated by Django 5.1.1 on 2024-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0006_alter_youtubepodcastvideo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubepodcast',
            name='custom_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
