# Generated by Django 5.1.1 on 2024-09-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_youtubepodcast_custom_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='youtubepodcastvideo',
            name='unique_title',
        ),
        migrations.RemoveConstraint(
            model_name='youtubepodcastvideo',
            name='unique_date_and_time',
        ),
    ]
