# Generated by Django 5.1 on 2026-08-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0007_troublerecord_warnstreamhandlerrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubepodcast',
            name='youtube_id',
            field=models.BooleanField(default=True),
        ),
    ]
