# Generated by Django 5.1.1 on 2024-09-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0008_remove_youtubepodcastvideo_unique_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubepodcast',
            name='unique_constraint',
            field=models.BooleanField(default=False),
        ),
    ]
