# Generated by Django 5.1 on 2026-10-04 16:28

import django.db.models.deletion
import podcasts.views.pstdatetimefield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_customlist_customlistentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSPodcastFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=10000, null=True)),
                ('url', models.CharField(max_length=10000)),
                ('language', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=1000)),
                ('owner_name', models.CharField(max_length=10000)),
                ('owner_email', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='customlistentry',
            name='podcast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.youtubepodcast'),
        ),
        migrations.CreateModel(
            name='RssPodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=1000, unique=True)),
                ('original_title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=10000, null=True)),
                ('duration', models.PositiveBigIntegerField()),
                ('date', podcasts.views.pstdatetimefield.PSTDateTimeField()),
                ('size', models.PositiveBigIntegerField()),
                ('link', models.CharField(max_length=5000)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.rsspodcastfeed')),
            ],
        ),
        migrations.AddField(
            model_name='customlistentry',
            name='external_podcast',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcasts.rsspodcastfeed'),
        ),
    ]
